name: Unit Tests

on:
    pull_request:
        branches: [main]

jobs:
    unit-tests:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: |
                yarn
                yarn test
